"""create table forum

Revision ID: 24cfbecf5bed
Revises: a304333c3fe1
Create Date: 2026-04-08 10:48:50.624596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "24cfbecf5bed"
down_revision: Union[str, Sequence[str], None] = "a304333c3fe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "forums",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_embedding", VECTOR(dim=1536), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ACADEMIC_SUPPORT",
                "CAMPUS_LIFE",
                "CAREER_SERVICES",
                "IT_TECHNOLOGY",
                "STUDENT_AFFAIRS",
                "GENERAL",
                name="forumcategory",
            ),
            nullable=False,
        ),
        sa.Column("posted_by", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forums_body_embedding_hnsw",
        "forums",
        ["body_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_forums_category"), "forums", ["category"], unique=False)
    op.create_index(op.f("ix_forums_posted_by"), "forums", ["posted_by"], unique=False)
    op.create_index(
        op.f("ix_forums_updated_at"), "forums", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forums_updated_at"), table_name="forums")
    op.drop_index(op.f("ix_forums_posted_by"), table_name="forums")
    op.drop_index(op.f("ix_forums_category"), table_name="forums")
    op.drop_index(
        "ix_forums_body_embedding_hnsw", table_name="forums", postgresql_using="hnsw"
    )
    op.drop_table("forums")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
