"""add expired_at in announcement

Revision ID: 7be64f14679e
Revises: 504c2be2188c
Create Date: 2026-05-07 16:09:52.245338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7be64f14679e"
down_revision: Union[str, Sequence[str], None] = "504c2be2188c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "announcements",
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        op.f("ix_announcements_expired_at"),
        "announcements",
        ["expired_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcements_expired_at"), table_name="announcements")
    op.drop_column("announcements", "expired_at")
    # ### end Alembic commands ###
