"""init tables

Revision ID: 7cba3f075e8c
Revises:
Create Date: 2026-04-10 19:30:48.714686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "7cba3f075e8c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "content_daily_views",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("FORUM", "QUESTION", "ANNOUNCEMENT", name="contenttype"),
            nullable=False,
        ),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("content_date", sa.Date(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_type", "content_id", "content_date", name="uq_content_daily_views"
        ),
    )
    op.create_index(
        "ix_cdv_date_content_cover",
        "content_daily_views",
        ["content_date", "content_type", "content_id"],
        unique=False,
        postgresql_include=["views_count"],
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.Enum("STUDENT", "STAFF", name="userrole"), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=512), nullable=False),
        sa.Column("email", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "announcements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_embedding", VECTOR(dim=768), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ACADEMIC",
                "IT_SERVICES",
                "EVENTS",
                "LIBRARY",
                "STUDENT_SERVICES",
                "FACILITIES",
                "CAREER_SERVICES",
                name="announcementcategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("INFO", "WARNING", "NEW", "URGENT", name="announcementpriority"),
            nullable=False,
        ),
        sa.Column("posted_by", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_announcements_body_embedding_hnsw",
        "announcements",
        ["body_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_announcements_category"), "announcements", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_announcements_posted_by"), "announcements", ["posted_by"], unique=False
    )
    op.create_index(
        op.f("ix_announcements_priority"), "announcements", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_announcements_updated_at"),
        "announcements",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("FORUM", "QUESTION", "ANNOUNCEMENT", name="contenttype"),
            nullable=False,
        ),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("parent_comment_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("posted_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_comment_id"],
            ["comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_views",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("FORUM", "QUESTION", "ANNOUNCEMENT", name="contenttype"),
            nullable=False,
        ),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_content_views_user_timestamp",
        "content_views",
        ["user_id", sa.literal_column("timestamp DESC")],
        unique=False,
        postgresql_include=["content_id", "content_type"],
    )
    op.create_table(
        "forums",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_embedding", VECTOR(dim=768), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ACADEMIC_SUPPORT",
                "CAMPUS_LIFE",
                "CAREER_SERVICES",
                "IT_TECHNOLOGY",
                "STUDENT_AFFAIRS",
                "GENERAL",
                name="forumcategory",
            ),
            nullable=False,
        ),
        sa.Column("posted_by", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forums_body_embedding_hnsw",
        "forums",
        ["body_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.create_index(op.f("ix_forums_category"), "forums", ["category"], unique=False)
    op.create_index(op.f("ix_forums_posted_by"), "forums", ["posted_by"], unique=False)
    op.create_index(
        op.f("ix_forums_updated_at"), "forums", ["updated_at"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_embedding", VECTOR(dim=768), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "IT_SERVICES",
                "LIBRARY",
                "HOUSING",
                "CAREER_SERVICES",
                "ACADEMIC",
                "DINING",
                "STUDENT_SERVICES",
                "TRANSPORTATION",
                name="questioncategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "COMPLETED", "CANCELED", name="questionstatus"),
            nullable=False,
        ),
        sa.Column("posted_by", sa.Integer(), nullable=False),
        sa.Column("views_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.Integer(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_questions_body_embedding_hnsw",
        "questions",
        ["body_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_questions_cancelled_at"), "questions", ["cancelled_at"], unique=False
    )
    op.create_index(
        op.f("ix_questions_cancelled_by"), "questions", ["cancelled_by"], unique=False
    )
    op.create_index(
        op.f("ix_questions_category"), "questions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_questions_completed_at"), "questions", ["completed_at"], unique=False
    )
    op.create_index(
        op.f("ix_questions_completed_by"), "questions", ["completed_by"], unique=False
    )
    op.create_index(
        op.f("ix_questions_posted_by"), "questions", ["posted_by"], unique=False
    )
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_index(
        op.f("ix_questions_updated_at"), "questions", ["updated_at"], unique=False
    )
    op.create_table(
        "reactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "content_type",
            sa.Enum("FORUM", "QUESTION", "ANNOUNCEMENT", name="contenttype"),
            nullable=False,
        ),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_type", "content_id", "user_id", name="uq_reactions_content_user"
        ),
    )
    op.create_index(
        "ix_reactions_content_user",
        "reactions",
        ["content_type", "content_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reactions_user_id"), "reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reactions_user_id"), table_name="reactions")
    op.drop_index("ix_reactions_content_user", table_name="reactions")
    op.drop_table("reactions")
    op.drop_index(op.f("ix_questions_updated_at"), table_name="questions")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_posted_by"), table_name="questions")
    op.drop_index(op.f("ix_questions_completed_by"), table_name="questions")
    op.drop_index(op.f("ix_questions_completed_at"), table_name="questions")
    op.drop_index(op.f("ix_questions_category"), table_name="questions")
    op.drop_index(op.f("ix_questions_cancelled_by"), table_name="questions")
    op.drop_index(op.f("ix_questions_cancelled_at"), table_name="questions")
    op.drop_index(
        "ix_questions_body_embedding_hnsw",
        table_name="questions",
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.drop_table("questions")
    op.drop_index(op.f("ix_forums_updated_at"), table_name="forums")
    op.drop_index(op.f("ix_forums_posted_by"), table_name="forums")
    op.drop_index(op.f("ix_forums_category"), table_name="forums")
    op.drop_index(
        "ix_forums_body_embedding_hnsw",
        table_name="forums",
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.drop_table("forums")
    op.drop_index(
        "ix_content_views_user_timestamp",
        table_name="content_views",
        postgresql_include=["content_id", "content_type"],
    )
    op.drop_table("content_views")
    op.drop_table("comments")
    op.drop_index(op.f("ix_announcements_updated_at"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_priority"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_posted_by"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_category"), table_name="announcements")
    op.drop_index(
        "ix_announcements_body_embedding_hnsw",
        table_name="announcements",
        postgresql_using="hnsw",
        postgresql_ops={"body_embedding": "vector_cosine_ops"},
    )
    op.drop_table("announcements")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "ix_cdv_date_content_cover",
        table_name="content_daily_views",
        postgresql_include=["views_count"],
    )
    op.drop_table("content_daily_views")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
